###################################
### GENERAL, HEADER & META TAGS ###
###################################

logo: ""                                                                        # Logo for your blog. Leave empty if you don't have one
blog_name: "Fidgety Blog"                                                       # Give your blog a meanungful name.
title: "Fidgety Blog - The things I get up to."                                 # Give your blog a meaningful title. This is used for the HTML title attribute
title_short: "Fidgety Blog"                                                        # Place the name of your blog or a short title here
short_description: "The things I get up to."                                    # Short description for your blog
meta_description: "Documenting the things I do, so others may find inspiration" # meta description tag
meta_author: "MrFidgety"                                                        # meta tag for author
keywords: "MrFdiegty, Fidgety, Blog"                                            # your keywords
og_logo: "https://opoloo.github.io/lines-engine/assets/images/lines-logo.jpg"   # OpenGraph logo
geo_position: "50.00; 8.27"                                                     # Geo tags for position and address
geo_address: "Melbourne, Australia"                                             # Geo tags for position and address


##############
### SOCIAL ###
##############

# Your Twitter and Google+ profile URL
# Leave empty if you don't want to display inside the footer
twitter_url: 'http://twitter.com/mr_fidgety'
gplus_url: ''


#################
### ATOM FEED ###
#################

feed_title: "Fidgety Blog - The things I get up to"        # give your feed a title
feed_logo: "https://opoloo.github.io/lines-engine/assets/images/lines-logo.jpg" # full URL to the feed logo. Aspect ratio should be 2:1
feed_favicon: "https://opoloo.github.io/lines-engine/assets/images/favicon.ico" # full URL to the favicon. Aspect ratio should be 1:1


#####################
### APP SPECIFICS ###
#####################

refresh_sitemap: false

hero_images: ["lines_default_01.png", "lines_default_02.png", "lines_default_03.png"]

articles_per_page: 10 # Pagination: How many articles should be desplayed per page?

# Your apps secret token. Generate a new one with 'rake secret' and paste it below
secret_token: "13bb4b5a71fcbd4c7958f13c0115796e3f54b8cc2a141bb896660a825a1bb713ac9ca09fafb4e42ce433679a59f5990073fbb953957e886747a7be0bb3a1f7c9"

# Carrierwave uploader
storage: :aws # or "aws" if using carrierwave-aws or "ftp" of using carrierwave-ftp

# Environment dependent configuration. Place your URLs here
development:
  host: "localhost:3000"
  from_email: 'noreply@example.com'
test:
  host: "test.local"
  from_email: 'noreply@example.com'
production:
  host: "mrfidgety.com"
  from_email: <%= ENV["MAILER_EMAIL"] %>
